### ISSUE TITLE
run in pipenv created venv

### ISSUE THREAD

**Issue by ahonnecke** [wbolster/emacs-python-pytest#8] opened 2018-05-20 00:49 UTC
apologies I'm missing something (I'm quite new to python), but I cannot figure out how to run this in a pipenv environment.  I have done pyenv-workon and selected an environment

I set the pythong pytest executable to "pipenv run py.test"
(I also tried pointing it to the venv)

From the command line
```
web on  pytest-in-ci [⇡$!] via 🐍 system took 4s
➜ pipenv run py.test --color=no 'server/dad/tests/test_graphql_auth.py::TestGraphQL::test_device_params'
======================================================================================== test session starts ========================================================================================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
Django settings: dad.settings (from environment variable)
rootdir: /Users/ahonnecke/Code/repos/web/server, inifile: pytest.ini
plugins: env-0.6.2, django-3.1.2
collected 1 item

server/dad/tests/test_graphql_auth.py .                                                                                                                                                       [100%]

===================================================================================== 1 passed in 1.19 seconds ======================================================================================

web on  pytest-in-ci [⇡$] via 🐍 system took 4s
```

From the popup:
```
cwd: /Users/ahonnecke/Code/repos/web/
cmd: pipenv run py.test --color=no 'server/dad/tests/test_graphql_auth.py::TestGraphQL::test_device_params'

Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
====================================== test session starts =======================================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/ahonnecke/Code/repos/web/server, inifile: pytest.ini
collecting 0 items / 1 errors                                                                    
============================================= ERRORS =============================================
________________________ ERROR collecting dad/tests/test_graphql_auth.py _________________________
ImportError while importing test module '/Users/ahonnecke/Code/repos/web/server/dad/tests/test_graphql_auth.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
server/dad/tests/test_graphql_auth.py:6: in <module>
    from dad.schema import schema
server/dad/schema.py:4: in <module>
    from django.utils import timezone
E   ModuleNotFoundError: No module named 'django'
==================================== 1 error in 0.06 seconds =====================================
ERROR: not found: /Users/ahonnecke/Code/repos/web/server/dad/tests/test_graphql_auth.py::TestGraphQL::test_device_params
(no name '/Users/ahonnecke/Code/repos/web/server/dad/tests/test_graphql_auth.py::TestGraphQL::test_device_params' in any of [<Module 'dad/tests/test_graphql_auth.py'>])
¯
```

I have django installed in the pipenv shell, but not locally

**Comment by wbolster** [comment] 2018-05-20 17:46
the output when running from emacs seems to indicate you have an active virtualenv. i suspect your environment setup in emacs itself is somehow broken, since python-pytest.el (by design) does not change the environment.

**Comment by wbolster** [comment] 2018-06-07 08:42
closing because no further information has been provided

**Comment by Frost** [comment] 2020-10-14 15:11
I had a similar issue, which I solved by setting `(setq python-pytest-executable "pyenv exec pytest")`. I'm not sure if that will help @ahonnecke, but it might help someone else having similar issues at least.

**Comment by wbolster** [comment] 2022-05-02 17:43
@mathieupost 

curious: what does ‘pipenv .... activated using direnv’ mean exactly? what does your envrc look like?

**Comment by mathieupost** [comment] 2022-05-02 17:53
@wbolster I'm using the [direnv module](https://github.com/doomemacs/doomemacs/tree/master/modules/tools/direnv) in doom, which is using [envrc](https://github.com/purcell/envrc) to integrate direnv.

My `.envrc` contains only this ([source](https://github.com/doomemacs/doomemacs/issues/1666#issuecomment-906730861)):
```
layout pipenv
```

**Comment by wbolster** [comment] 2022-05-02 18:03
okay, that looks straightforward 🙃 what does your `$PATH` look like? and how is pytest installed? because typically pytest should be available in the path after installation, and this emacs package would then simply pick it up.

**Comment by mathieupost** [comment] 2022-05-02 18:13
Hahah maybe not the most natural way of using emacs, but it works for me coming from neovim :)

I've installed pytest by adding it to the `[dev-packages]` list in the `Pipfile` of my project. So, it only in the `$PATH` after pipenv is activated. Could this be the problem? Although the direnv module of doom should take care of that before the python and python-pytest package is loaded I think.

**Comment by wbolster** [comment] 2022-05-02 18:41
not familiar with doom. (but coming from vim myself originally)

isn't the point of activating that the path is correct? this package simply runs pytest by default, without any path, so it should pick the first match in the path.

can you `echo $PATH` in your envrc and inspect the direnv buffer in emacs? and also output in shell?

**Comment by wbolster** [comment] 2022-05-02 18:41
note that the `echo` should be the very last line in envrc

**Comment by mathieupost** [comment] 2022-05-02 20:00
The bin folder from the virtual environment is added to the beginning of the `$PATH` in both emacs and the shell, but I think the problem is maybe not with the python-pytest package. Because this is the output when I run pytest in the terminal:
```
❯ pytest --color=yes 'tests/state/commit_state_test.py::TestCommitState::test_commit_state'
================================================================ test session starts =================================================================
platform darwin -- Python 3.8.9, pytest-7.1.1, pluggy-1.0.0
rootdir: /Users/mathieu/Dev/src/tudelft.nl/stateflow
plugins: anyio-3.5.0, timeout-2.1.0, mock-3.7.0
collected 0 items / 1 error                                                                                                                          

======================================================================= ERRORS =======================================================================
_________________________________________________ ERROR collecting tests/state/commit_state_test.py __________________________________________________
ImportError while importing test module '/Users/mathieu/Dev/src/tudelft.nl/stateflow/tests/state/commit_state_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/state/commit_state_test.py:6: in <module>
    from stateflow.dataflow.address import FunctionAddress, FunctionType
E   ModuleNotFoundError: No module named 'stateflow'
============================================================== short test summary info ===============================================================
ERROR tests/state/commit_state_test.py
================================================================== 1 error in 0.12s ==================================================================
ERROR: not found: /Users/mathieu/Dev/src/tudelft.nl/stateflow/tests/state/commit_state_test.py::TestCommitState::test_commit_state
(no name '/Users/mathieu/Dev/src/tudelft.nl/stateflow/tests/state/commit_state_test.py::TestCommitState::test_commit_state' in any of [<Module tests/state/commit_state_test.py>])
```
```
❯ python -m pytest 'tests/state/commit_state_test.py::TestCommitState::test_commit_state'
================================================================ test session starts =================================================================
platform darwin -- Python 3.8.9, pytest-7.1.1, pluggy-1.0.0
rootdir: /Users/mathieu/Dev/src/tudelft.nl/stateflow
plugins: anyio-3.5.0, timeout-2.1.0, mock-3.7.0
collected 1 item                                                                                                                                     

tests/state/commit_state_test.py .                                                                                                             [100%]

================================================================= 1 passed in 3.17s ==================================================================
```
```
❯ which python
/Users/mathieu/.local/share/virtualenvs/stateflow-kgcsblk2/bin/python
```
```
❯ which pytest
/Users/mathieu/.local/share/virtualenvs/stateflow-kgcsblk2/bin/pytest
```

So for some reason it seems that I always need to prepend the `pytest` command with `python -m `. I never noticed this before, since the plugin I used in neovim didn't have this problem for some reason. So, that brings me back to [this answer](https://stackoverflow.com/a/50170600) on StackOverflow which states that this is needed to add the project root to the `sys.path` of python. I think that `pyenv exec pytest` which @Frost used, also fixes this.

**Comment by wbolster** [comment] 2022-05-09 20:06
this is kinda puzzling. `pytest` is in the right place in the path, and it's installed _inside_ the _active_ venv it seems.

have you actually _installed_ your package (e.g. `pip install --editable .`) properly in your venv? what does `python -c 'import foo'` (with the right name) do?

tbh i think your issues have nothing to do with `python-pytest.el`.

are you aware of this? https://docs.pytest.org/en/6.2.x/pythonpath.html#invoking-pytest-versus-python-m-pytest

**Comment by mathieupost** [comment] 2022-05-09 22:05
> have you actually installed your package (e.g. pip install --editable .)

I’ve not tried that yet. 

> tbh i think your issues have nothing to do with python-pytest.el.
> are you aware of this? https://docs.pytest.org/en/6.2.x/pythonpath.html#invoking-pytest-versus-python-m-pytest

Yes I found that as well, which is what I tried to tell in my last comment. Sorry if that was not clear. 

Maybe a solution could be to use `python -m pytest` by default? But I’m not sure if there could be cases where that would not work for some reason. 

Otherwise I’ll just set it to that in my own config :)

**Comment by wbolster** [comment] 2022-05-10 15:48
i will keep the default to `pytest`, not `python -m pytest`, even though i think the latter is generally better to run python tools with the correct (venv) environment etc.

the reason is simply that it's the default in the upstream docs: https://docs.pytest.org/en/7.1.x/getting-started.html

**Comment by mathieupost** [comment] 2022-05-11 08:10
That makes sense!

Maybe something could be added to the README. If you want I will make a PR to add a `troubleshooting` section containing the suggestion to add `(setq python-pytest-executable "python -m pytest")` when encountering this error.

**Closed** 2022-07-20 19:22 UTC
Labels: invalid, question
